### ISSUE TITLE
can not run the plugin

### ISSUE THREAD

**Issue by adellife** [papersgpt/papersgpt-for-zotero#11]
After installing the plugin, a window showing a verification process appeared. Then, a small error window appeared on Zotero. I have tried many times to reinstall and restart both Zotero and my laptop, but it still does not work.

**Comment by papersgpt** [comment]
What is your operating system?

**Comment by hellobigworld600** [comment]
What's your zotero version? Are you using the latest version zotero 7. If not, update zotero 7 to the latest version, then reinstall the plugin to see if it's OK.

**Comment by adellife** [comment]
Hi, I used the latest version of the plugin and Zotero 7. I removed Zotero and other plugins, restarted my Mac, and reinstalled them. Suddenly, it worked.

**Comment by ljeagle** [comment]
Congrats! If any problem comes, never hesitate to issue here or email us, thanks!
