### ISSUE TITLE
Does not have other options except OpenAI

### ISSUE THREAD

**Issue by flashshare** [papersgpt/papersgpt-for-zotero#16]
The plugin working well yesterday, but I have recently update the Zotero Beta, then there is no more option like Gemini, the one I used yesterday

![image](https://github.com/user-attachments/assets/20a886b6-d263-4e26-9e89-ad1e21a1d49b)

My current Zotero Version: 7.0.11-beta.3+b5310d5f0 (64-bit)
I try to install the official Zotero-7.0.10_x64_setup, but it has the same problem

**Comment by papersgpt** [comment]
Got it, I try to reproduce your problem now.

**Comment by papersgpt** [comment]
> The plugin working well yesterday, but I have recently update the Zotero Beta, then there is no more option like Gemini, the one I used yesterday
> 
> ![image](https://private-user-images.githubusercontent.com/79207918/391924794-20a886b6-d263-4e26-9e89-ad1e21a1d49b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDY2MjMsIm5iZiI6MTczMzI0NjMyMywicGF0aCI6Ii83OTIwNzkxOC8zOTE5MjQ3OTQtMjBhODg2YjYtZDI2My00ZTI2LTllODktYWQxZTIxYTFkNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE3MTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNzRlMjhmMjA3MjE2NWQxYTAzYWJkYzYyNWFkZWJhZTlmM2QyOWRkNzVmOGNmYTBhYzg5YTdkMmM2N2I4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2X3KpSJQl5ufy7ZD7C77HI4gimJ5LwDSDqfrqRXTjdo)
> 
> My current Zotero Version: 7.0.11-beta.3+b5310d5f0 (64-bit) I try to install the official Zotero-7.0.10_x64_setup, but it has the same problem

We have fixed the bug that gemini and claude would not be shown after the plugin has been turned off in Windows. You can try the binary of v0.0.2(https://github.com/papersgpt/papersgpt-for-zotero/releases/download/papersgpt-v0.0.2/papersgpt-v0.0.2.xpi)

**Comment by flashshare** [comment]
Thanks. working perfectly now
