### ISSUE TITLE
 'Customized' can't work from my side,not sure how to config it.

### ISSUE THREAD

**Issue by hellobigworld600** [papersgpt/papersgpt-for-zotero#23]
'Customized' can't work from my side, not sure how to config it. I ask question but the papersgpt don't response.
![image](https://github.com/user-attachments/assets/66c159be-c553-48f6-8850-776e588953fe)

**Comment by papersgpt** [comment]
The API URL is for OpenAI is https://api.openai.com/v1/chat/completions, you can try the new one.

**Comment by hellobigworld600** [comment]
It works with the new URL,thx!
